# Generated by Django 4.1.7 on 2023-07-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mysell'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='新用户', max_length=20),
        ),
    ]
